### ISSUE TITLE
对象里的内容显示不出来

### ISSUE THREAD

**Issue by jourdon** [nineyang/dd#1]
![image](https://user-images.githubusercontent.com/24295670/30848436-bc9749aa-a2d1-11e7-96fc-239e75bc5d32.png)

![image](https://user-images.githubusercontent.com/24295670/30848408-a7e96d08-a2d1-11e7-9fcd-f18e7dd99d51.png)

**Comment by nineyang** [comment]
多谢提醒，已经修复。

![image](https://user-images.githubusercontent.com/19544562/30853246-dafd53ca-a273-11e7-863c-5937826abe1e.png)


![image](https://user-images.githubusercontent.com/19544562/30853220-c985e97c-a273-11e7-82f5-b99b1afeb9d0.png)
